language: node_js
node_js:
- '0.10'
before_install:
- sudo apt-get update -qq
- sudo apt-get install -qq libbluetooth-dev
before_deploy:
- npm install ws browserify
- mkdir deploy
- node_modules/.bin/browserify -s Connector connector.js > deploy/meshblu-tickr.js
deploy:
  matrix:
  - provider: s3
    access_key_id: AKIAIT4X4NDGM2WVL6VA
    secret_access_key:
      secure: DAOcqcwrtxo5CoTGp5E6A8zODrmAdSpipNx7ZcNMeB2VTMJ1hyDG/p1R9fO8kgFPMUcg1NqXcjKPt0RGgYeQwxguJhz2vk5Do+cadT3SIO7+nQHSfs0D+Yc6vu2bucXptuSczIE4kRSb9PTHAiO3QNmuERqX8n4Hvm8Lp7bg9uI=
    bucket: gateblu
    region: us-west-2
    skip_cleanup: true
    local-dir: deploy
    upload-dir: javascript
    on:
      tags: true
      all_branches: true
  - provider: npm
    skip_cleanup: true
    clean_up: false
    email: roy.v.water@gmail.com
    api_key:
      secure: RRJKRKFC9JIvdxbkDKrdUPDwmPQc5SzfguQEDdopykTxRoDG4FQKdVnFSGzsoqyHxFDZmNZNrtem54C1bWFUhFSmYR9EZow9hzM+wrtrVFS3FpdL94AnZo+nweOCCfShccg+z50D7Bw8pFxbul9ui/lSqHZepRWCVaNkK2ueeC0=
    on:
      tags: true
      all_branches: true
