language: node_js
sudo: true
node_js:
- '0.10'
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq libbluetooth-dev
before_deploy:
  - npm install ws browserify coffeeify
  - mkdir -p deploy/meshblu-ble-heartrate/latest
  - mkdir -p deploy/meshblu-ble-heartrate/$TRAVIS_TAG
  - node_modules/.bin/browserify -s Connector connector.js > deploy/meshblu-ble-heartrate/latest/meshblu-ble-heartrate.js
  - gzip deploy/meshblu-ble-heartrate/latest/meshblu-ble-heartrate.js
  - mv deploy/meshblu-ble-heartrate/latest/meshblu-ble-heartrate.js.gz deploy/meshblu-ble-heartrate/latest/meshblu-ble-heartrate.js
  - cp deploy/meshblu-ble-heartrate/latest/meshblu-ble-heartrate.js deploy/meshblu-ble-heartrate/$TRAVIS_TAG/meshblu-ble-heartrate.js
deploy:
  - provider: s3
    access_key_id: AKIAIT4X4NDGM2WVL6VA
    secret_access_key:
      secure: "f9/kr1VnllDk2VDAeuKt/4PGmw01qi74LPyZkN80VJoU3aIi4dF+ZbXKX00TTJ89MpSMvWdycPpkasRcPDRs58FGtJSFJb4VwJa/tmh/AyfEsRgI/RdpTbt/HMx64km0F/asgktGrE5kdY/FfVkKubqPaZPPpMFFYm/M48mU9ak="
    bucket: octoblu-cdn
    region: us-west-2
    skip_cleanup: true
    detect_encoding: true
    local-dir: deploy
    upload-dir: js
    on:
      tags: true
      all_branches: true
  - provider: npm
    skip_cleanup: true
    clean_up: false
    email: serveradmin@octoblu.com
    api_key:
      secure: "TUEEwPyS/jPywgi4IHNwJZoWnI6JIjhHcQtTlYA/hnhod6hylIYM9bR02J857qvlrev5VMtByC46BI1nr9VipKvxw0MJeqC1RbH2fS7iFjLl9CJb1eEdkeFNYdf4w5jp1fCKjRiplP/0jVeGpyiblK3xA5iwZfFJhZdKpJHyx0o="
    on:
      tags: true
      all_branches: true
