language: node_js
sudo: true
node_js:
- '0.10'
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq libbluetooth-dev
before_deploy:
  - npm install ws browserify coffeeify
  - mkdir -p deploy/meshblu-tickr/latest
  - mkdir -p deploy/meshblu-tickr/$TRAVIS_TAG
  - node_modules/.bin/browserify -s Connector connector.js > deploy/meshblu-tickr/latest/meshblu-tickr.js
  - gzip deploy/meshblu-tickr/latest/meshblu-tickr.js
  - mv deploy/meshblu-tickr/latest/meshblu-tickr.js.gz deploy/meshblu-tickr/latest/meshblu-tickr.js
  - cp deploy/meshblu-tickr/latest/meshblu-tickr.js deploy/meshblu-tickr/$TRAVIS_TAG/meshblu-tickr.js
deploy:
  - provider: s3
    access_key_id: AKIAIT4X4NDGM2WVL6VA
    secret_access_key:
      secure: fcrrjAYLD9B8xpr2obD67u8YSDl8Q/u0olYD/4fmTLUhKioM6Lh4Ivf77+N40RDUrriHw2Nuvtn7/IgM8QWxJYRnXZb5qgSgbpwt8joIoFtXvgjyahtnFp8UdrkOfvpxi6A9iU/7KL2Jm4gulLrgrEVkq0TR/k2HCnF0n/RKeZU=
    bucket: octoblu-cdn
    region: us-west-2
    skip_cleanup: true
    local-dir: deploy
    upload-dir: js
    on:
      tags: true
      all_branches: true
  - provider: npm
    skip_cleanup: true
    clean_up: false
    email: roy.v.water@gmail.com
    api_key:
      secure: RRJKRKFC9JIvdxbkDKrdUPDwmPQc5SzfguQEDdopykTxRoDG4FQKdVnFSGzsoqyHxFDZmNZNrtem54C1bWFUhFSmYR9EZow9hzM+wrtrVFS3FpdL94AnZo+nweOCCfShccg+z50D7Bw8pFxbul9ui/lSqHZepRWCVaNkK2ueeC0=
    on:
      tags: true
      all_branches: true
